# Generated by Django 3.2 on 2022-08-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_otp',
            field=models.PositiveIntegerField(blank=True, max_length=6, null=True, verbose_name='mobile otp'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Designates whether this users email is verified. ', verbose_name='email verified'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_verified',
            field=models.BooleanField(default=False, help_text='Designates whether this users mobile is verified. ', verbose_name='mobile verified'),
        ),
    ]
