# Generated by Django 3.2 on 2022-09-01 08:07

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0002_auto_20220830_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_generated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in this format: '+919999999999'. Up to 13 digits allowed.", regex='^\\+\\d{12,13}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_otp',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='mobile otp'),
        ),
    ]
