# Generated by Django 3.2 on 2022-09-01 08:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0003_auto_20220901_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_generated_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 1, 8, 8, 20, 439408, tzinfo=utc)),
        ),
    ]
