# Generated by Django 3.2 on 2022-09-01 08:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0004_alter_user_otp_generated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='otp_generated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
